blobla/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

# handler404 = 'blobla.views.error_404'
# handler500 = 'blobla.views.error_500'

main/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path("<slug:slug>/", views.post_detail, name="post_detail"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = ((0, "Draft"), (1, "Publish"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    updated_on = models.DateTimeField(auto_now=True)
    image = models.ImageField(null=True, blank=True, upload_to="images/")
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("post_detail", kwargs={"slug": str(self.slug)})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=18)
    email = models.EmailField(max_length=50)
    body = models.TextField(max_length=510)
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return "Comment {} by {}".format(self.body, self.name)

main/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name", "email", "body")

blobla/views.py
from django.shortcuts import render

def error_404(request, exception):
    data = {}
    response = render(request, '404.html', data)
    response.status_code = 404
    return response


def error_500(request):
    data = {}
    response = render(request, '500.html', data)
    response.status_code = 500
    return response

main/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.contrib.auth import authenticate, login

from .forms import CommentForm
from .models import Post

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"
    paginate_by = 3


# class PostDetail(generic.DetailView):
#     model = Post
#     template_name = 'post_detail.html'


def post_detail(request, slug):
    template_name = "post_detail.html"
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True).order_by("created_on")
    new_comment = None
    # Comment posted
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(
        request,
        template_name,
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
        },
    )

templates/index.html
{% extends "base.html" %}

{% block page_title %}Blobla - Home{% endblock page_title %}

{% block content %}
    <section class="mn-top-20">
        <div class="main-container">
            <div class="greeting-label h-200">
                <h2>Welcome to the "BloBla"!</h2>
            </div>
        </div>
    </section>

    <main class="mn-top-20 mn-bottom-20">
        <div class="main-container">
            <div class="flex-hl-row main-row">
                <div class="flex-vl-row flex-cl-2">
                    {% if post_list %}
                        {% for post in post_list %}
                            <a href="{% url 'post_detail' post.slug  %}" class="cboard post pn-25 flex-vl-row mn-bottom-20">
                                <div class="post-details mn-bottom-10">
                                    <h3>{{ post.title }}</h3>
                                    <p>{{ post.created_on}}</p>
                                </div>
                                {% if post.image %}
                                    <div class="mn-bottom-10">
                                        <img class="photo-media" src="{{ post.image.url | safe }}">
                                    </div>
                                {% endif %}
                                <span class="post-content line-clamp">{{ post.content | safe | slice:":100" }}</span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="cboard  h-200 pn-25 mn-bottom-20">
                            <h2>Nothing yet...</h2>
                        </div>
                    {% endif %}
                    {% if is_paginated %}
                        <nav class="page-navigation pn-10">
                            <ul>
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}" class="cboard">&lt; PREV </a></li>
                                {% endif %}
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}" class="cboard"> NEXT &gt;</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
                {% block sidebar %}
                    {% include 'sidebar.html' %}
                {% endblock sidebar %}
            </div>
        </div>
    </main>
{%endblock%}

templates/post_detail.html
{% extends 'base.html' %} 
{% load static %}

{% block page_title %}Blobla - {{ post.title | slice:":50" }}{% endblock page_title%}

{% block content %}

    <main class="mn-top-20">
        <div class="main-container">
            <div class="flex-hl-row main-row">
                <div class="flex-vl-row flex-cl-2">
                    <div href="post.html" class="cboard post pn-25 flex-vl-row mn-bottom-20">
                        <div class="post-details mn-bottom-10">
                            <h3>{% block title %} {{ post.title }} {% endblock title %}</h3>
                            <p>{{ post.created_on }}</p>
                        </div>
                        {% if post.image %}
                        <div class="mn-bottom-10">
                            <img class="photo-media" src="{{ post.image.url | safe }}">
                        </div>
                        {% endif %}
                        <span class="post-content">{{ post.content | safe }}</span>
                    </div>
                    <div class="cboard flex-vl-row pn-25 mn-bottom-20">
                        {% with comments.count as total_comments %}
                            <h3 class="mn-bottom-20">{{ total_comments }} Comments</h3>
                        {% endwith %} 
                        <div class="flex-vl-row">
                            {% for comment in comments %}
                                <div class="comment flex-hl-row mn-bottom-20">
                                    <div class="comments-avatar mn-right-10">
                                        <img src="{% static 'img/unknown-user.png' %}">
                                    </div>
                                    <div class="comments-details flex-vl-row">
                                        <h4 class="mn-bottom-5">{{ comment.name }}</h4>
                                        <span>{{ comment.body | linebreaks }}</span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="comment-board cboard pn-25 mn-bottom-20 flex-vl-row">
                        {% if new_comment %}
                            <div class="alert" role="alert">Your comment is awaiting moderation!</div>
                        {% else %}
                            <form action="." method="post" class="flex-vl-row">
                                {% csrf_token %}
                                <h3 class="mn-bottom-20 underline">Add a comment</h3>
                                <div class="flex-hl-row mn-bottom-10">
                                    <input type="text" name="name" class="flex-cl-1" id="id_name" required maxlength="18" placeholder="Name" value="{{ comment.name }}">
                                    <input type="email" name="email" class="flex-cl-1" id="id_email" required maxlength="50" placeholder="Email" value="{{ comment.email }}">
                                </div>
                                <textarea name="body" class="mn-bottom-10" id="id_body" cols="30" rows="10" required maxlength="500" placeholder="Your comment..." value="{{ comment.body }}"></textarea>
                                <div class="send-btn-wrapp">
                                    <button class="default-btn" type="submit">Send</button>
                                </div>
                            </form>
                        {% endif %}
                    </div>
                </div>
                {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
            </div>
        </div>
    </main>

{% endblock content %}

templates/sidebar.html
{% load static %}

{% block sidebar %}
    <div class="flex-vl-row flex-cl-1 author-details-wrapp mn-left-20">
        <div class="cboard author-details pn-25 flex-vl-row">
            <div class="flex-cl-1 author-photo mn-bottom-10">
                <img class="photo-media" src="{% static 'img/ava.png' %}">
            </div>
            <div class="flex-cl-2">
                <h3 class="mn-bottom-5">Yusuf Safarov</h3>
                <p>Simple guy who want to get high from life... live, enjoy, and work in your free time)</p>
            </div>
        </div>
    </div>
{% endblock sidebar %}